logging:
  level: INFO
  loggers:
    io.rtr.cuny: DEBUG

database:
  driverClass: org.h2.Driver
  user: test
  password: test
  url: jdbc:h2:./target/members

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

